#!/usr/bin/with-contenv bash

setcap 'cap_net_bind_service=+ep' /usr/bin/python3.8

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

echo "Starting Home Assistant."
redirect_cmd exec s6-setuidgid abc /usr/bin/hass \
	-c /config
